### PR TITLE
Adding pedantic 1.9.0

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by tejainece** [comment]
Hi,

I suggest disabling "Don't type local variable" lint rule. I find explicit specification of variable types intuitive when it is not an initialisation statement.

**Comment by domesticmouse** [comment]
Fair enough, put back the explicit local variable types. PTAL

**Comment by domesticmouse** [comment]
Ping?

**Review by tejainece — APPROVED** [review]
LGTM

**Comment by tejainece** [comment]
Thanks for the fix!

Published it as `2.0.2`.

**Pull request merged**
